//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaunchVehicle.BackendServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehicle", Namespace="http://schemas.datacontract.org/2004/07/Backend")]
    [System.SerializableAttribute()]
    public partial class Vehicle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double OrbitRadiusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LaunchVehicle.BackendServiceReference.Payload PayloadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpacecraftStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double OrbitRadius {
            get {
                return this.OrbitRadiusField;
            }
            set {
                if ((this.OrbitRadiusField.Equals(value) != true)) {
                    this.OrbitRadiusField = value;
                    this.RaisePropertyChanged("OrbitRadius");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LaunchVehicle.BackendServiceReference.Payload Payload {
            get {
                return this.PayloadField;
            }
            set {
                if ((object.ReferenceEquals(this.PayloadField, value) != true)) {
                    this.PayloadField = value;
                    this.RaisePropertyChanged("Payload");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpacecraftStatus {
            get {
                return this.SpacecraftStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.SpacecraftStatusField, value) != true)) {
                    this.SpacecraftStatusField = value;
                    this.RaisePropertyChanged("SpacecraftStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payload", Namespace="http://schemas.datacontract.org/2004/07/Backend")]
    [System.SerializableAttribute()]
    public partial class Payload : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayloadStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayloadStatus {
            get {
                return this.PayloadStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.PayloadStatusField, value) != true)) {
                    this.PayloadStatusField = value;
                    this.RaisePropertyChanged("PayloadStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Telemetry", Namespace="http://schemas.datacontract.org/2004/07/Backend")]
    [System.SerializableAttribute()]
    public partial class Telemetry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AltitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TemperatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeToOrbitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Altitude {
            get {
                return this.AltitudeField;
            }
            set {
                if ((this.AltitudeField.Equals(value) != true)) {
                    this.AltitudeField = value;
                    this.RaisePropertyChanged("Altitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Temperature {
            get {
                return this.TemperatureField;
            }
            set {
                if ((this.TemperatureField.Equals(value) != true)) {
                    this.TemperatureField = value;
                    this.RaisePropertyChanged("Temperature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeToOrbit {
            get {
                return this.TimeToOrbitField;
            }
            set {
                if ((this.TimeToOrbitField.Equals(value) != true)) {
                    this.TimeToOrbitField = value;
                    this.RaisePropertyChanged("TimeToOrbit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BackendServiceReference.IBackendServices", CallbackContract=typeof(LaunchVehicle.BackendServiceReference.IBackendServicesCallback))]
    public interface IBackendServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/AddSpaceCraft", ReplyAction="http://tempuri.org/IBackendServices/AddSpaceCraftResponse")]
        string AddSpaceCraft(LaunchVehicle.BackendServiceReference.Vehicle vehicle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/AddSpaceCraft", ReplyAction="http://tempuri.org/IBackendServices/AddSpaceCraftResponse")]
        System.Threading.Tasks.Task<string> AddSpaceCraftAsync(LaunchVehicle.BackendServiceReference.Vehicle vehicle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/GetAllSpacecraft", ReplyAction="http://tempuri.org/IBackendServices/GetAllSpacecraftResponse")]
        LaunchVehicle.BackendServiceReference.Vehicle[] GetAllSpacecraft();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/GetAllSpacecraft", ReplyAction="http://tempuri.org/IBackendServices/GetAllSpacecraftResponse")]
        System.Threading.Tasks.Task<LaunchVehicle.BackendServiceReference.Vehicle[]> GetAllSpacecraftAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/CheckSpacecraftExists", ReplyAction="http://tempuri.org/IBackendServices/CheckSpacecraftExistsResponse")]
        long CheckSpacecraftExists(string vehicleName, string payloadName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/CheckSpacecraftExists", ReplyAction="http://tempuri.org/IBackendServices/CheckSpacecraftExistsResponse")]
        System.Threading.Tasks.Task<long> CheckSpacecraftExistsAsync(string vehicleName, string payloadName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/GetAddedSpacecraft", ReplyAction="http://tempuri.org/IBackendServices/GetAddedSpacecraftResponse")]
        LaunchVehicle.BackendServiceReference.Vehicle[] GetAddedSpacecraft();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/GetAddedSpacecraft", ReplyAction="http://tempuri.org/IBackendServices/GetAddedSpacecraftResponse")]
        System.Threading.Tasks.Task<LaunchVehicle.BackendServiceReference.Vehicle[]> GetAddedSpacecraftAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/UpdateSpacecraft1", ReplyAction="http://tempuri.org/IBackendServices/UpdateSpacecraft1Response")]
        void UpdateSpacecraft1(string vehicleName, string column, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/UpdateSpacecraft1", ReplyAction="http://tempuri.org/IBackendServices/UpdateSpacecraft1Response")]
        System.Threading.Tasks.Task UpdateSpacecraft1Async(string vehicleName, string column, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/UpdateSpacecraft2", ReplyAction="http://tempuri.org/IBackendServices/UpdateSpacecraft2Response")]
        void UpdateSpacecraft2(string vehicleName, string column1, string value1, string column2, string value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/UpdateSpacecraft2", ReplyAction="http://tempuri.org/IBackendServices/UpdateSpacecraft2Response")]
        System.Threading.Tasks.Task UpdateSpacecraft2Async(string vehicleName, string column1, string value1, string column2, string value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/UpdateSpacecraft3", ReplyAction="http://tempuri.org/IBackendServices/UpdateSpacecraft3Response")]
        void UpdateSpacecraft3(string vehicleName, string column1, string value1, string column2, string value2, string column3, string value3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/UpdateSpacecraft3", ReplyAction="http://tempuri.org/IBackendServices/UpdateSpacecraft3Response")]
        System.Threading.Tasks.Task UpdateSpacecraft3Async(string vehicleName, string column1, string value1, string column2, string value2, string column3, string value3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/LaunchSpacecraft", ReplyAction="http://tempuri.org/IBackendServices/LaunchSpacecraftResponse")]
        void LaunchSpacecraft(string vehicleName, string dsnDashboardName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/LaunchSpacecraft", ReplyAction="http://tempuri.org/IBackendServices/LaunchSpacecraftResponse")]
        System.Threading.Tasks.Task LaunchSpacecraftAsync(string vehicleName, string dsnDashboardName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/GetAllOnlineSpacecraft", ReplyAction="http://tempuri.org/IBackendServices/GetAllOnlineSpacecraftResponse")]
        LaunchVehicle.BackendServiceReference.Vehicle[] GetAllOnlineSpacecraft();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/GetAllOnlineSpacecraft", ReplyAction="http://tempuri.org/IBackendServices/GetAllOnlineSpacecraftResponse")]
        System.Threading.Tasks.Task<LaunchVehicle.BackendServiceReference.Vehicle[]> GetAllOnlineSpacecraftAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/GetSpacecraft", ReplyAction="http://tempuri.org/IBackendServices/GetSpacecraftResponse")]
        LaunchVehicle.BackendServiceReference.Vehicle GetSpacecraft(string vehicleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/GetSpacecraft", ReplyAction="http://tempuri.org/IBackendServices/GetSpacecraftResponse")]
        System.Threading.Tasks.Task<LaunchVehicle.BackendServiceReference.Vehicle> GetSpacecraftAsync(string vehicleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/GetAllOnlinePayload", ReplyAction="http://tempuri.org/IBackendServices/GetAllOnlinePayloadResponse")]
        LaunchVehicle.BackendServiceReference.Vehicle[] GetAllOnlinePayload();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/GetAllOnlinePayload", ReplyAction="http://tempuri.org/IBackendServices/GetAllOnlinePayloadResponse")]
        System.Threading.Tasks.Task<LaunchVehicle.BackendServiceReference.Vehicle[]> GetAllOnlinePayloadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/UpdateTelemetryMap", ReplyAction="http://tempuri.org/IBackendServices/UpdateTelemetryMapResponse")]
        void UpdateTelemetryMap(string vehicleName, LaunchVehicle.BackendServiceReference.Telemetry telemetry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/UpdateTelemetryMap", ReplyAction="http://tempuri.org/IBackendServices/UpdateTelemetryMapResponse")]
        System.Threading.Tasks.Task UpdateTelemetryMapAsync(string vehicleName, LaunchVehicle.BackendServiceReference.Telemetry telemetry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/GetTelemetryOfVehicle", ReplyAction="http://tempuri.org/IBackendServices/GetTelemetryOfVehicleResponse")]
        LaunchVehicle.BackendServiceReference.Telemetry GetTelemetryOfVehicle(string vehicleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/GetTelemetryOfVehicle", ReplyAction="http://tempuri.org/IBackendServices/GetTelemetryOfVehicleResponse")]
        System.Threading.Tasks.Task<LaunchVehicle.BackendServiceReference.Telemetry> GetTelemetryOfVehicleAsync(string vehicleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/RequestTelemetryOfVehicle", ReplyAction="http://tempuri.org/IBackendServices/RequestTelemetryOfVehicleResponse")]
        void RequestTelemetryOfVehicle(LaunchVehicle.BackendServiceReference.Vehicle vehicle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/RequestTelemetryOfVehicle", ReplyAction="http://tempuri.org/IBackendServices/RequestTelemetryOfVehicleResponse")]
        System.Threading.Tasks.Task RequestTelemetryOfVehicleAsync(LaunchVehicle.BackendServiceReference.Vehicle vehicle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/SendCommandToVehicle", ReplyAction="http://tempuri.org/IBackendServices/SendCommandToVehicleResponse")]
        void SendCommandToVehicle(LaunchVehicle.BackendServiceReference.Vehicle vehicle, string command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/SendCommandToVehicle", ReplyAction="http://tempuri.org/IBackendServices/SendCommandToVehicleResponse")]
        System.Threading.Tasks.Task SendCommandToVehicleAsync(LaunchVehicle.BackendServiceReference.Vehicle vehicle, string command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/ConnectToBackend", ReplyAction="http://tempuri.org/IBackendServices/ConnectToBackendResponse")]
        void ConnectToBackend(string vehicleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/ConnectToBackend", ReplyAction="http://tempuri.org/IBackendServices/ConnectToBackendResponse")]
        System.Threading.Tasks.Task ConnectToBackendAsync(string vehicleName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBackendServicesCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/ReceiveCommand", ReplyAction="http://tempuri.org/IBackendServices/ReceiveCommandResponse")]
        void ReceiveCommand(LaunchVehicle.BackendServiceReference.Vehicle vehicle, string command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBackendServices/SendCommand", ReplyAction="http://tempuri.org/IBackendServices/SendCommandResponse")]
        void SendCommand(LaunchVehicle.BackendServiceReference.Vehicle vehicle, string command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBackendServicesChannel : LaunchVehicle.BackendServiceReference.IBackendServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BackendServicesClient : System.ServiceModel.DuplexClientBase<LaunchVehicle.BackendServiceReference.IBackendServices>, LaunchVehicle.BackendServiceReference.IBackendServices {
        
        public BackendServicesClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public BackendServicesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public BackendServicesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public BackendServicesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public BackendServicesClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string AddSpaceCraft(LaunchVehicle.BackendServiceReference.Vehicle vehicle) {
            return base.Channel.AddSpaceCraft(vehicle);
        }
        
        public System.Threading.Tasks.Task<string> AddSpaceCraftAsync(LaunchVehicle.BackendServiceReference.Vehicle vehicle) {
            return base.Channel.AddSpaceCraftAsync(vehicle);
        }
        
        public LaunchVehicle.BackendServiceReference.Vehicle[] GetAllSpacecraft() {
            return base.Channel.GetAllSpacecraft();
        }
        
        public System.Threading.Tasks.Task<LaunchVehicle.BackendServiceReference.Vehicle[]> GetAllSpacecraftAsync() {
            return base.Channel.GetAllSpacecraftAsync();
        }
        
        public long CheckSpacecraftExists(string vehicleName, string payloadName) {
            return base.Channel.CheckSpacecraftExists(vehicleName, payloadName);
        }
        
        public System.Threading.Tasks.Task<long> CheckSpacecraftExistsAsync(string vehicleName, string payloadName) {
            return base.Channel.CheckSpacecraftExistsAsync(vehicleName, payloadName);
        }
        
        public LaunchVehicle.BackendServiceReference.Vehicle[] GetAddedSpacecraft() {
            return base.Channel.GetAddedSpacecraft();
        }
        
        public System.Threading.Tasks.Task<LaunchVehicle.BackendServiceReference.Vehicle[]> GetAddedSpacecraftAsync() {
            return base.Channel.GetAddedSpacecraftAsync();
        }
        
        public void UpdateSpacecraft1(string vehicleName, string column, string status) {
            base.Channel.UpdateSpacecraft1(vehicleName, column, status);
        }
        
        public System.Threading.Tasks.Task UpdateSpacecraft1Async(string vehicleName, string column, string status) {
            return base.Channel.UpdateSpacecraft1Async(vehicleName, column, status);
        }
        
        public void UpdateSpacecraft2(string vehicleName, string column1, string value1, string column2, string value2) {
            base.Channel.UpdateSpacecraft2(vehicleName, column1, value1, column2, value2);
        }
        
        public System.Threading.Tasks.Task UpdateSpacecraft2Async(string vehicleName, string column1, string value1, string column2, string value2) {
            return base.Channel.UpdateSpacecraft2Async(vehicleName, column1, value1, column2, value2);
        }
        
        public void UpdateSpacecraft3(string vehicleName, string column1, string value1, string column2, string value2, string column3, string value3) {
            base.Channel.UpdateSpacecraft3(vehicleName, column1, value1, column2, value2, column3, value3);
        }
        
        public System.Threading.Tasks.Task UpdateSpacecraft3Async(string vehicleName, string column1, string value1, string column2, string value2, string column3, string value3) {
            return base.Channel.UpdateSpacecraft3Async(vehicleName, column1, value1, column2, value2, column3, value3);
        }
        
        public void LaunchSpacecraft(string vehicleName, string dsnDashboardName) {
            base.Channel.LaunchSpacecraft(vehicleName, dsnDashboardName);
        }
        
        public System.Threading.Tasks.Task LaunchSpacecraftAsync(string vehicleName, string dsnDashboardName) {
            return base.Channel.LaunchSpacecraftAsync(vehicleName, dsnDashboardName);
        }
        
        public LaunchVehicle.BackendServiceReference.Vehicle[] GetAllOnlineSpacecraft() {
            return base.Channel.GetAllOnlineSpacecraft();
        }
        
        public System.Threading.Tasks.Task<LaunchVehicle.BackendServiceReference.Vehicle[]> GetAllOnlineSpacecraftAsync() {
            return base.Channel.GetAllOnlineSpacecraftAsync();
        }
        
        public LaunchVehicle.BackendServiceReference.Vehicle GetSpacecraft(string vehicleName) {
            return base.Channel.GetSpacecraft(vehicleName);
        }
        
        public System.Threading.Tasks.Task<LaunchVehicle.BackendServiceReference.Vehicle> GetSpacecraftAsync(string vehicleName) {
            return base.Channel.GetSpacecraftAsync(vehicleName);
        }
        
        public LaunchVehicle.BackendServiceReference.Vehicle[] GetAllOnlinePayload() {
            return base.Channel.GetAllOnlinePayload();
        }
        
        public System.Threading.Tasks.Task<LaunchVehicle.BackendServiceReference.Vehicle[]> GetAllOnlinePayloadAsync() {
            return base.Channel.GetAllOnlinePayloadAsync();
        }
        
        public void UpdateTelemetryMap(string vehicleName, LaunchVehicle.BackendServiceReference.Telemetry telemetry) {
            base.Channel.UpdateTelemetryMap(vehicleName, telemetry);
        }
        
        public System.Threading.Tasks.Task UpdateTelemetryMapAsync(string vehicleName, LaunchVehicle.BackendServiceReference.Telemetry telemetry) {
            return base.Channel.UpdateTelemetryMapAsync(vehicleName, telemetry);
        }
        
        public LaunchVehicle.BackendServiceReference.Telemetry GetTelemetryOfVehicle(string vehicleName) {
            return base.Channel.GetTelemetryOfVehicle(vehicleName);
        }
        
        public System.Threading.Tasks.Task<LaunchVehicle.BackendServiceReference.Telemetry> GetTelemetryOfVehicleAsync(string vehicleName) {
            return base.Channel.GetTelemetryOfVehicleAsync(vehicleName);
        }
        
        public void RequestTelemetryOfVehicle(LaunchVehicle.BackendServiceReference.Vehicle vehicle) {
            base.Channel.RequestTelemetryOfVehicle(vehicle);
        }
        
        public System.Threading.Tasks.Task RequestTelemetryOfVehicleAsync(LaunchVehicle.BackendServiceReference.Vehicle vehicle) {
            return base.Channel.RequestTelemetryOfVehicleAsync(vehicle);
        }
        
        public void SendCommandToVehicle(LaunchVehicle.BackendServiceReference.Vehicle vehicle, string command) {
            base.Channel.SendCommandToVehicle(vehicle, command);
        }
        
        public System.Threading.Tasks.Task SendCommandToVehicleAsync(LaunchVehicle.BackendServiceReference.Vehicle vehicle, string command) {
            return base.Channel.SendCommandToVehicleAsync(vehicle, command);
        }
        
        public void ConnectToBackend(string vehicleName) {
            base.Channel.ConnectToBackend(vehicleName);
        }
        
        public System.Threading.Tasks.Task ConnectToBackendAsync(string vehicleName) {
            return base.Channel.ConnectToBackendAsync(vehicleName);
        }
    }
}
